# Generated by Django 5.0.4 on 2024-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishikawa_diagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishikawadiagram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
