# Generated by Django 5.0.4 on 2024-04-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id_incident', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('impact', models.CharField(max_length=100)),
                ('vidmage', models.FileField(blank=True, null=True, upload_to='incident_vidmages/')),
            ],
        ),
    ]
