# Generated by Django 5.0.4 on 2024-04-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_alter_incident_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incident',
            table='incident',
        ),
    ]
