# Generated by Django 5.0.4 on 2024-04-18 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_alter_incident_table'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
